version: '3.4'

services:
    db:
        image: postgres:10
        environment:
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: formazion
            POSTGRES_DB: formazion_dev
        volumes:
            - ./docker/.data/db:/var/lib/postgresql
        ports:
            - 55432:5432

    php:
        build: ./docker/php
        links:
            - db:db
        ports:
            - 59000:9000
        volumes:
            - .:/var/www/formazion:cached
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini

    web:
        image: nginx:1.15
        ports:
            - 8000:80
        depends_on:
            - php
        volumes:
            - .:/var/www/formazion
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    adminer:
        image: adminer:4
        links:
            - db:db
        ports:
            - 8080:8080
