Formazion\Models\Company:
    type: entity
    table: formazion.companies
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        numberAddress:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: number_address
        street:
            type: string
            nullable: false
            length: 125
            options:
                fixed: false
        postalCode:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: postal_code
        city:
            type: string
            nullable: false
            length: 125
            options:
                fixed: false
        country:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
    lifecycleCallbacks: {  }
    oneToMany:
        persons:
            targetEntity: person
            mappedBy: company