Formazion\Models\Session:
    repositoryClass: Formazion\Repository\SessionRepository
    type: entity
    table: formazion.sessions
    indexes:
        IDX_40CC11C43BF5B0C2:
            columns:
                - formations_id
        IDX_40CC11C48E2368AB:
            columns:
                - rooms_id
        IDX_40CC11C441807E1D:
            columns:
                - teacher_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: AUTO
    fields:
        starting:
            type: datetime
            nullable: false
        ending:
            type: datetime
            nullable: false
        hoursPerformed:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: hours_performed
        report:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
    manyToOne:
        formations:
            targetEntity: Formation
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                formations_id:
                    referencedColumnName: id
            orphanRemoval: false
        rooms:
            targetEntity: Room
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                rooms_id:
                    referencedColumnName: id
            orphanRemoval: false
        teacher:
            targetEntity: Person
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                teacher_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        persons:
            targetEntity: Person
            mappedBy: sessionStudents
