Formation:
    type: entity
    table: formazion.formations
    indexes:
        IDX_6AE76748BF899CC4:
            columns:
                - responsible_professor_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
    manyToOne:
        responsibleProfessor:
            targetEntity: person
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                responsible_professor_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
    oneToMany:
        session:
            targetEntity: session
            mappedBy: formations