-- MySQL Script generated by MySQL Workbench
-- Sat Mar 23 17:32:14 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema formazion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema formazion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS  "formazion"  ;

-- -----------------------------------------------------
-- Table "formazion"."companies"
-- -----------------------------------------------------
CREATE TABLE  "formazion"."companies" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(45) NOT NULL,
  "number_address" INT NOT NULL,
  "street" VARCHAR(125) NOT NULL,
  "postal_code" INT NOT NULL,
  "city" VARCHAR(125) NOT NULL,
  "country" VARCHAR(60) NOT NULL
  );


-- -----------------------------------------------------
-- Table "formazion"."persons"
-- -----------------------------------------------------
CREATE TABLE  "formazion"."persons" (
  "id" SERIAL PRIMARY KEY,
  "firstname" VARCHAR(45) NOT NULL,
  "lastname" VARCHAR(45) NOT NULL,
  "role" VARCHAR(45) NOT NULL,
  "companies_id" INT NULL,
  CONSTRAINT "fk_customers_companies1"
    FOREIGN KEY ("companies_id")
    REFERENCES "formazion"."companies" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "formazion"."formations"
-- -----------------------------------------------------
CREATE TABLE  "formazion"."formations" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(45) NOT NULL,
  "responsible_professor_id" INT NOT NULL,
  CONSTRAINT "fk_formations_persons1"
    FOREIGN KEY ("responsible_professor_id")
    REFERENCES "formazion"."persons" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "formazion"."rooms"
-- -----------------------------------------------------
CREATE TABLE  "formazion"."rooms" (
  "id" SERIAL PRIMARY KEY,
  "number" INT NOT NULL
);


-- -----------------------------------------------------
-- Table "formazion"."sessions"
-- -----------------------------------------------------
CREATE TABLE  "formazion"."sessions" (
  "id" SERIAL PRIMARY KEY,
  "starting" TIMESTAMP NOT NULL,
  "ending" TIMESTAMP NOT NULL,
  "hours_performed" int NULL,
  "report" VARCHAR(255) NULL,
  "formations_id" INT NOT NULL,
  "rooms_id" INT NOT NULL,
  "teacher_id" INT NOT NULL,
  CONSTRAINT "fk_sessions_formations1"
    FOREIGN KEY ("formations_id")
    REFERENCES "formazion"."formations" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_sessions_rooms1"
    FOREIGN KEY ("rooms_id")
    REFERENCES "formazion"."rooms" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_sessions_customers1"
    FOREIGN KEY ("teacher_id")
    REFERENCES "formazion"."persons" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "formazion"."students_sessions"
-- -----------------------------------------------------
CREATE TABLE  "formazion"."students_sessions" (
  "id" SERIAL PRIMARY KEY ,
  "students_id" INT NOT NULL,
  "sessions_id" INT NOT NULL,
  "note" int NULL,
  CONSTRAINT "fk_customers_formations_customers1"
    FOREIGN KEY ("students_id")
    REFERENCES "formazion"."persons" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_students_sessions_sessions1"
    FOREIGN KEY ("sessions_id")
    REFERENCES "formazion"."sessions" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


DROP SEQUENCE IF EXISTS "formazion"."companies_id_sequence";
CREATE SEQUENCE  "formazion"."companies_id_sequence";
ALTER TABLE "formazion"."companies" ALTER COLUMN "id" SET DEFAULT NEXTVAL('"formazion"."companies_id_sequence"');
DROP SEQUENCE IF EXISTS "formazion"."persons_id_sequence";
CREATE SEQUENCE  "formazion"."persons_id_sequence";
ALTER TABLE "formazion"."persons" ALTER COLUMN "id" SET DEFAULT NEXTVAL('"formazion"."persons_id_sequence"');
DROP SEQUENCE IF EXISTS "formazion"."formations_id_sequence";
CREATE SEQUENCE  "formazion"."formations_id_sequence";
ALTER TABLE "formazion"."formations" ALTER COLUMN "id" SET DEFAULT NEXTVAL('"formazion"."formations_id_sequence"');
DROP SEQUENCE IF EXISTS "formazion"."rooms_id_sequence";
CREATE SEQUENCE  "formazion"."rooms_id_sequence";
ALTER TABLE "formazion"."rooms" ALTER COLUMN "id" SET DEFAULT NEXTVAL('"formazion"."rooms_id_sequence"');
DROP SEQUENCE IF EXISTS "formazion"."sessions_id_sequence";
CREATE SEQUENCE  "formazion"."sessions_id_sequence";
ALTER TABLE "formazion"."sessions" ALTER COLUMN "id" SET DEFAULT NEXTVAL('"formazion"."sessions_id_sequence"');
DROP SEQUENCE IF EXISTS "formazion"."students_sessions_id_sequence";
CREATE SEQUENCE  "formazion"."students_sessions_id_sequence";
ALTER TABLE "formazion"."students_sessions" ALTER COLUMN "id" SET DEFAULT NEXTVAL('"formazion"."students_sessions_id_sequence"');
